import 'package:firestore_odm/firestore_odm.dart';
import 'package:flutter/widgets.dart';
import 'package:moonforge/core/database/odm.dart';
import 'package:moonforge/core/models/data/campaign.dart';
import 'package:moonforge/core/models/data/schema.dart';
import 'package:moonforge/core/models/return_message.dart';
import 'package:moonforge/core/providers/auth_providers.dart';
import 'package:moonforge/core/services/app_router.dart';
import 'package:moonforge/core/utils/logger.dart';
import 'package:moonforge/features/campaign/controllers/campaign_provider.dart';
import 'package:provider/provider.dart';

/// Creates a new Campaign in Firestore and navigates to the Campaign edit page.
///
/// - Persists the newly created campaign id using [selectedCampaignIdProvider]
/// - Navigates using typed routes: [CampaignEditRoute]
///
/// Parameters [name] and [description] are optional and default to a minimal
/// placeholder if not provided. No user-facing toasts are shown here to
/// avoid introducing non-localized strings; errors are logged.
Future<ReturnMessage<Campaign?>> createCampaignAndOpenEditor(
  BuildContext context, {
  String? name,
  String? description,
}) async {
  final authProvider = Provider.of<AuthProvider>(context, listen: false);
  final campaignProvider = Provider.of<CampaignProvider>(
    context,
    listen: false,
  );
  final odm = Odm.instance;

  try {
    final ownerUid = authProvider.user?.id;
    if (ownerUid == null) {
      logger.w('createCampaign aborted: user not authenticated');
      return ReturnMessage.failure('Bitte zuerst anmelden.', null);
    }
    // Capture target location before async operations.
    final location = const CampaignEditRoute().location;

    final data = Campaign(
      id: FirestoreODM.autoGeneratedId,
      // will be __FIRESTORE_ODM_AUTO_GENERATED_ID__ and be replaced by server
      name: name?.trim().isNotEmpty == true ? name!.trim() : '',
      description: description ?? '',
      content: null,
      ownerUid: ownerUid,
      memberUids: <String>[ownerUid],
      // Use server timestamp to align across clients
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rev: 0,
    );

    await odm.campaigns.insert(data);
    // Fetch the most recently created campaign for this owner
    final createdCampaign = await odm.campaigns
        .where(($) => $.ownerUid(isEqualTo: ownerUid))
        .orderBy(($) => ($.createdAt(descending: true),))
        .limit(1)
        .get()
        .then((snapshot) => snapshot.first);

    // Persist selected id so dependent screens can resolve the document
    campaignProvider.setCurrentCampaign(createdCampaign);

    // Navigate to the campaign edit screen without using context now
    AppRouter.router.go(location);

    return ReturnMessage.success(
      "Campaign created successfully",
      createdCampaign,
    );
  } catch (e, st) {
    logger.e('Failed to create campaign', error: e, stackTrace: st);
    return ReturnMessage.failure('Failed to create campaign: $e', null);
  }
}
