import 'package:flutter/material.dart';
import 'package:moonforge/core/services/app_router.dart';
import 'package:moonforge/core/services/notification_service.dart';
import 'package:moonforge/core/utils/logger.dart';
import 'package:moonforge/data/db/app_db.dart';
import 'package:moonforge/l10n/app_localizations.dart';

Future<void> createAdventure(BuildContext context, Campaign campaign) async {
  final l10n = AppLocalizations.of(context)!;
  final odm = Odm.instance;
  final chapters = await odm.campaigns
      .doc(campaign.id)
      .chapters
      .orderBy((o) => (o.order(),))
      .get();
  if (chapters.isEmpty) {
    if (context.mounted) {
      notification.info(context, title: Text(l10n.noChaptersYet));
    }
    return;
  }
  Chapter selected = chapters.first;
  final last = await odm.campaigns
      .doc(selected.id)
      .adventures
      .orderBy((o) => (o.order(descending: true),))
      .limit(1)
  final nextOrder = last.isNotEmpty ? (last.first.order + 1) : 1;
  final nameController = TextEditingController();
  final confirmed = await showDialog<bool>(
    context: context,
    builder: (ctx) {
      return StatefulBuilder(
        builder: (ctx, setState) => AlertDialog(
          title: Text('${l10n.createAdventure}: Nr. $nextOrder'),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              DropdownButtonFormField<String>(
                initialValue: selected.id,
                decoration: InputDecoration(labelText: l10n.selectChapter),
                items: [
                  for (final c in chapters)
                    DropdownMenuItem(value: c.id, child: Text(c.name)),
                ],
                onChanged: (id) {
                  final found = chapters.firstWhere(
                    (c) => c.id == (id ?? selected.id),
                  );
                  setState(() => selected = found);
                },
              ),
              const SizedBox(height: 12),
              TextField(
                controller: nameController,
                decoration: InputDecoration(labelText: l10n.name),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(ctx).pop(false),
              child: Text(l10n.cancel),
            ),
            FilledButton(
              onPressed: () => Navigator.of(ctx).pop(true),
              child: Text(l10n.create),
          ],
        ),
      );
    },
  );
  if (confirmed != true) return;
  final name = nameController.text.trim();
  if (name.isEmpty) return;
  try {
    final adv = Adventure(
      id: FirestoreODM.autoGeneratedId,
      name: name,
      order: nextOrder,
      summary: '',
      content: null,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rev: 0,
    );
    await odm.campaigns
        .doc(campaign.id)
        .chapters
        .doc(selected.id)
        .adventures
        .insert(adv);
    final created = await odm.campaigns
        .where((f) => f.name(isEqualTo: name))
        .orderBy((o) => (o.createdAt(descending: true),))
        .limit(1)
        .get()
        .then((v) => v.isNotEmpty ? v.first : null);
    if (!context.mounted) return;
    notification.success(context, title: Text(l10n.createAdventure));
    if (created != null) {
      AdventureRoute(
        chapterId: selected.id,
        adventureId: created.id,
      ).go(context);
  } catch (e, st) {
    logger.e('Create adventure failed', error: e, stackTrace: st);
    notification.error(context, title: Text('Failed: $e'));
}
