// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY']!,
    appId: '1:654145881639:web:b05031a4c17d94cf417002',
    messagingSenderId: '654145881639',
    projectId: 'moonforge-bc',
    authDomain: 'moonforge-bc.firebaseapp.com',
    storageBucket: 'moonforge-bc.firebasestorage.app',
    measurementId: 'G-GLLPWKR1NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFvEFiyUiaMrOzTFxigK1oMF0yFZM7eTk',
    appId: '1:654145881639:android:30ec344d665f22c7417002',
    messagingSenderId: '654145881639',
    projectId: 'moonforge-bc',
    storageBucket: 'moonforge-bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5-B3nGrbIbzm-Mp-9h1mQiBCy2cf2CyM',
    appId: '1:654145881639:ios:570081412f74e751417002',
    messagingSenderId: '654145881639',
    projectId: 'moonforge-bc',
    storageBucket: 'moonforge-bc.firebasestorage.app',
    iosClientId:
        '654145881639-iftev2vvfhsft8v9aldpqrjp2l1cv123.apps.googleusercontent.com',
    iosBundleId: 'de.bruckcode.moonforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5-B3nGrbIbzm-Mp-9h1mQiBCy2cf2CyM',
    appId: '1:654145881639:ios:570081412f74e751417002',
    messagingSenderId: '654145881639',
    projectId: 'moonforge-bc',
    storageBucket: 'moonforge-bc.firebasestorage.app',
    iosClientId:
        '654145881639-iftev2vvfhsft8v9aldpqrjp2l1cv123.apps.googleusercontent.com',
    iosBundleId: 'de.bruckcode.moonforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcXyxETa4ZXPEkd_9aCUl5VQkcdUe4P1I',
    appId: '1:654145881639:web:5a8626278a23bcbd417002',
    messagingSenderId: '654145881639',
    projectId: 'moonforge-bc',
    authDomain: 'moonforge-bc.firebaseapp.com',
    storageBucket: 'moonforge-bc.firebasestorage.app',
    measurementId: 'G-RM630YNKHQ',
  );
}
