targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      drift_dev:
        options:
          store_date_time_values_as_text: true      # ISO-8601 in SQLite (recommended for web)
      flutter_gen_runner:
        options:

