targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      drift_dev:
        options:
          # Generate code for Drift tables and DAOs
          generate_connect_constructor: true
      flutter_gen_runner:
        options:

