targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      isar_generator:
        options:
          # Generate code for Isar collections
      flutter_gen_runner:
        options:

