import 'package:firestore_odm/firestore_odm.dart';
import 'package:flutter/material.dart';
import 'package:moonforge/core/database/odm.dart';
import 'package:moonforge/core/models/data/adventure.dart';
import 'package:moonforge/core/models/data/campaign.dart';
import 'package:moonforge/core/models/data/scene.dart';
import 'package:moonforge/core/models/data/schema.dart';
import 'package:moonforge/core/services/app_router.dart';
import 'package:moonforge/core/services/notification_service.dart';
import 'package:moonforge/core/utils/logger.dart';
import 'package:moonforge/l10n/app_localizations.dart';

/// Create a new scene in a specific chapter context
Future<void> createSceneInChapter(
  BuildContext context,
  Campaign campaign,
  String chapterId,
) async {
  final l10n = AppLocalizations.of(context)!;
  final odm = Odm.instance;

  final adventures = await odm.campaigns
      .doc(campaign.id)
      .chapters
      .doc(chapterId)
      .adventures
      .orderBy((o) => (o.order(),))
      .get();

  if (adventures.isEmpty) {
    if (context.mounted) {
      notification.info(context, title: Text(l10n.noAdventuresYet));
    }
    return;
  }

  Adventure selectedAdventure = adventures.first;
  final titleController = TextEditingController();

  final confirmed = await showDialog<bool>(
    context: context,
    builder: (ctx) {
      return StatefulBuilder(
        builder: (ctx, setState) => AlertDialog(
          title: Text(l10n.createScene),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              DropdownButtonFormField<String>(
                initialValue: selectedAdventure.id,
                decoration: InputDecoration(labelText: l10n.selectAdventure),
                items: [
                  for (final a in adventures)
                    DropdownMenuItem(value: a.id, child: Text(a.name)),
                ],
                onChanged: (id) {
                  final adv = adventures.firstWhere(
                    (a) => a.id == (id ?? selectedAdventure.id),
                  );
                  setState(() => selectedAdventure = adv);
                },
              ),
              const SizedBox(height: 12),
              TextField(
                controller: titleController,
                autofocus: true,
                decoration: InputDecoration(labelText: l10n.name),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(ctx).pop(false),
              child: Text(l10n.cancel),
            ),
            FilledButton(
              onPressed: () => Navigator.of(ctx).pop(true),
              child: Text(l10n.create),
            ),
          ],
        ),
      );
    },
  );
  if (confirmed != true) return;
  final title = titleController.text.trim();
  if (title.isEmpty) return;

  try {
    final scene = Scene(
      id: FirestoreODM.autoGeneratedId,
      title: title,
      content: null,
      mentions: const <Map<String, dynamic>>[],
      mediaRefs: const <Map<String, dynamic>>[],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rev: 0,
    );
    await odm.campaigns
        .doc(campaign.id)
        .chapters
        .doc(chapterId)
        .adventures
        .doc(selectedAdventure.id)
        .scenes
        .insert(scene);

    final created = await odm.campaigns
        .doc(campaign.id)
        .chapters
        .doc(chapterId)
        .adventures
        .doc(selectedAdventure.id)
        .scenes
        .where((f) => f.title(isEqualTo: title))
        .orderBy((o) => (o.createdAt(descending: true),))
        .limit(1)
        .get()
        .then((v) => v.isNotEmpty ? v.first : null);

    if (!context.mounted) return;
    notification.success(context, title: Text(l10n.createScene));
    if (created != null) {
      SceneRoute(
        chapterId: chapterId,
        adventureId: selectedAdventure.id,
        sceneId: created.id,
      ).go(context);
    }
  } catch (e, st) {
    logger.e('Create scene failed', error: e, stackTrace: st);
    if (!context.mounted) return;
    notification.error(context, title: Text('Failed: $e'));
  }
}
