name: Deploy Website to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'
      - '.github/workflows/deploy-website.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If a Personal Access Token is provided, try to auto-enable Pages to avoid "Get Pages site failed" errors.
      # Create a repo secret named PAGES_TOKEN with a PAT that has at least "repo" scope (or Pages write) to use this path.
      - name: Setup Pages (enable if token provided)
        if: ${{ secrets.PAGES_TOKEN != '' }}
        uses: actions/configure-pages@v5
        with:
          enablement: true
          token: ${{ secrets.PAGES_TOKEN }}

      # Fallback: configure Pages without enablement (requires Pages to already be enabled in repo settings)
      - name: Setup Pages
        if: ${{ secrets.PAGES_TOKEN == '' }}
        uses: actions/configure-pages@v5

      # If you need a build step, add it here. For static content we just upload the folder.
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
